### ISSUE TITLE
'Database is re-entrant' crashes happen when fetching data from the database in an observable's `onNext`

### ISSUE THREAD

**Issue by mayurdzk** [RxSwiftCommunity/RxGRDB#16]
Hey, I've attached a sample project that demonstrates my use case: I'm trying to access objects from the database in the `onNext` event of an observable (that I get from RxGRDB). This causes the app to crash with the 'Database is re-entrant' error.

This project doesn't crash though but the GRDB version I'm using with my Swift 3.2 project does. I was wondering why this is? Does the `onNext` block hold on to a db object internally? If so, how can I access values from the database within a subscription's `onNext`? 
[TestingRxRentrance.zip](https://github.com/RxSwiftCommunity/RxGRDB/files/1526901/TestingRxRentrance.zip)

**Comment by mayurdzk** [comment]
I've verified that the re-entrant crash does happen with the last versions of GRDB compatible with Swift 3. Here's the versions I used in my Podfile:
<img width="232" alt="screen shot 2017-12-04 at 5 36 24 pm" src="https://user-images.githubusercontent.com/10453316/33552176-fa98b26a-d919-11e7-87d1-7443eeab0ac1.png">

**Comment by groue** [comment]
Hello @mayurdzk,

Thanks a lot for the sample project. It uses the latest GRDB (2.4.0) and RxGRDB (0.7.0), and does not exhibit the bug you are talking about.

Yet the bug was indeed there in RxGRDB 0.6.0. It has been fixed in v0.7.0. The [changelog](https://github.com/RxSwiftCommunity/RxGRDB/blob/master/CHANGELOG.md) says:

> Fixed: Observables that emit fetched values used to emit their first element on the wrong dispatch queue when their synchronizedStart option is true. That first element is now correctly emitted on the subscription dispatch queue.

What happens in RxGRDB 0.6.0 is that the first value is emitted in a reserved database queue from which one can not invoke DatabaseQueue (because GRDB forbids reentrancy). In RxGRDB 0.7.0, the first value would be, in your sample project, correctly emitted in the main queue, from which you can freely invoke a DatabaseQueue method.

If you can't upgrade GRDB and RxGRDB, here is some advice:

1. avoid calling database methods from the onNext block of database value observables:

    ```swift
    Foo.all().rx.fetchAll(in: dbQueue)
        .subscribe(onNext: { foos in
             // NO
            dbQueue.inDatabase { ... }
        })
    ```

2. If you really need to perform several fetches after a database change notification with RxGRDB 0.6.0, then use the `rx.change` method, which gives you a database connection:

    ```swift
    Foo.all().rx.changes(in: dbQueue)
        .map { db -> ([Foo], [Bar]) in
            return try (
                Bar.fetchAll(db),
                Foo.fetchAll(db)
            )
        }
        .observeOn(MainScheduler.instance)
        .subscribe(onNext: { (foos, bars) in
            print(foos)
            print(bars)
        })
    ```

3. A general advice when using GRDB: avoid hiding database queues inside methods, as below:
    
    ```swift
    // CALLING FOR TROUBLE
    func getAllBars() -> [Bar] {
        return dbQueue.inDatabase { db in
            return try! Bar.fetchAll(db)
        }
    }
    ```
    
    This will create several problems:
    
    The first one is the "Database methods are not reentrant" fatal error that you have already met.
    
    The second one is multi-threading surprises. Please have a read of the [Concurrency](https://github.com/groue/GRDB.swift/blob/master/README.md#concurrency) documentation chapter, especially at the "concurrency rule 2" that this kind of method actively prevents.

**Comment by mayurdzk** [comment]
Hey @groue, thank you so much for replying.

I understand the issue better now, I'll work around it for now with a `DispatchQueue.main.async { /* code to fetch objects */ }` block of code until I can update to 0.7.0.
Also, thanks for the link to the concurrency chapter--it gives me a clearer perspective on things.

Thanks for all your great work, cheers! 😁

**Comment by groue** [comment]
You're welcome Mayur! Happy RxGRDB :-)
