### ISSUE TITLE
Using RxGRDB with TestScheduler

### ISSUE THREAD

**Issue by davidkraus** [RxSwiftCommunity/RxGRDB#22]
Hey,
is there a reason why the scheduler overloads are restricted to a SerialDispatchQueueScheduler?
I want to setup a unit test with an inMemory SQLite GRDB instance and somehow i can't get it to work. I'm not too familiar with GRDB/Scheduler internals so i don't know if this is even possible? Do you have any thoughts on this?

**Comment by groue** [comment]
Hello @davidkraus 

I'm not familiar enough with schedulers to answer your question yet. We're both RxSwift schedulers newbies :-)

I know that SerialDispatchQueueScheduler provides the kind of guarantees that RxGRDB needs. But a more general protocol may still honor the very struct scheduling requirements of SQLite. I'll need to have a look.

**Comment by groue** [comment]
OK @davidkraus, let's investigate what those schedulers are :metal:

The [Schedulers](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Schedulers.md) documentation is useful, but also not very clear. There are sentences like the following, which is impossible to understand:

> In case the scheduler is concurrent, Rx's observeOn and subscribeOn operators will make sure everything works perfectly.

The [ReactiveX page on Schedulers](http://reactivex.io/documentation/scheduler.html) isn't better.

Either you're not supposed to know what a scheduler is, or schedulers are very hard to describe.

Fortunately, there are hints that the fundamental job of RxSwift schedulers is to execute single-threaded items of work, **one at a time** (with the consequence that items can not be reentrantly nested):

> If you use some scheduler that Rx can prove is serial, it will be able to perform additional optimizations.

> If some parent frame on the call stack is already running CurrentThreadScheduler.instance.schedule(state) { }, the scheduled action will be enqueued and executed when the currently running action and all previously enqueued actions have finished executing.

I don't know if this guarantee is particular to RxSwift, or to all Reactive schedulers in general.

---

What are the available Scheduler protocols?

- [ImmediateSchedulerType](https://github.com/ReactiveX/RxSwift/blob/4.1.2/RxSwift/ImmediateSchedulerType.swift)
    - [SchedulerType](https://github.com/ReactiveX/RxSwift/blob/4.1.2/RxSwift/SchedulerType.swift)

They can schedule actions "immediately", "relatively", "periodically", or "recursively". My interpretations:

- "immediately" has an action enqueued for being executed as soon as possible.
- "relatively" has an action enqueued for being executed after a delay.
- "periodically" deals with timers.
- "recursively" deals with tail recursion.

There's still nothing that *defines* what a scheduler is, but there is nothing that invalidates the hypothesis that "schedulers execute single-threaded items of work, one at a time, and avoid reentrancy".

---

I think we'll need @kzaher to know, for good, what is the scheduler contract.

---

But I have enough information now for answering your question :smile:

Since RxGRDB just needs serial execution (the guarantee that no two scheduled items of work overlap), I can replace `SerialDispatchQueueScheduler` with `ImmediateSchedulerType` in the RxGRDB APIs.

A new release will ship shortly. And thanks for your question!

**Comment by groue** [comment]
Done, you can use any scheduler you want with [RxGRDB v0.9.0](https://github.com/RxSwiftCommunity/RxGRDB/blob/master/CHANGELOG.md).

**Comment by davidkraus** [comment]
Wow thanks, you are fast ;).
I just tested our code with v0.9.0 and it works now 🎉.

Ok so the Scheduler thing: As far as i understand it the Scheduler does not magically introduce any kind of concurrency - And i think they can't because this would interfere with the Observable contract (onNext sequentially and on the same thread). If you want to parallelise your code you have to use a combination of flatMap and observeOn (see https://tomstechnicalblog.blogspot.de/2015/11/rxjava-achieving-parallelization.html).

**Comment by groue** [comment]
David, you're totally right! The contract I have been looking for in schedulers was actually defined on observables themselves :-)
