### ISSUE TITLE
Module file's minimum deployment target 

### ISSUE THREAD

**Issue by kotvaska** [RxSwiftCommunity/RxGRDB#3]
I'm trying to use module RxGRDB, but I have a problem. My project deployment target is 10.0, but requirements of module says that minimum is ios8.0

> Requirements: iOS 8.0+ / OSX 10.10+ / watchOS 2.0+ • Xcode 8.3+ • Swift 3.1

Error log: 

`Error:(10, 8) module file's minimum deployment target is ios10.3 v10.3: /Users/.../Carthage/Build/iOS/RxGRDB.framework/Modules/RxGRDB.swiftmodule/x86_64.swiftmodule`

**Comment by groue** [comment]
Hello @kotvaska 

RxGRDB is not currently available through Carthage, because Carthage isn't able to handle GRDB.

If you feel like an Xcode and Carthage guru, please send a pull request to GRDB or Carthage, so that they match together. More information at https://github.com/Carthage/Carthage/issues/1867.

If not, please install RxGRDB with CocoaPods, as [documented](https://github.com/RxSwiftCommunity/RxGRDB#installation). This should fix your deployment issues.

**Comment by kotvaska** [comment]
@groue, thank you for the answer! I think I can close this issue.

I see now. I don't feel like a guru, but I'll try to help!
