### ISSUE TITLE
Testing a fetch call within a Promise leads to unwanted results.

### ISSUE THREAD

**Issue by mayurdhaka-suryasoftware** [RxSwiftCommunity/RxGRDB#36]
Hey @groue!

I've attached a sample project that illustrates the bug I'm describing here.

Run the test `testExample` in the tests target of the project. You'll see that the call to fetching all `Foo` objects succeeds outside before the [PromiseKit](https://github.com/mxcl/PromiseKit) `done` block but it fails inside the block (there's a crash).

Here are some other behaviours I've noticed that should help:
- Using a simple `Foo.all().rx.fetchAll(in: dbPool)` in the `fooObservableViaPool` method *does* work as intended.
- Increasing the time out time in the test to 200 seconds leads to the test not crashing but it does succeed either (it waits for all the 200 seconds).
- In the test, if you change the syntax from 
`let foos = try! database.fooObservableViaPool().toBlocking().first()!`
to
`let foos = try! database.fooObservableViaPool().subscribe(onNext:{ foos in /.../ })`
it works!
- In my main app, I migrated from RxGRDB `0.7.0` to `0.10.0`. This issue didn't exist in `0.7.0`.

Let me know if there's any more information you need from me. Thank you for your time! 😃

[TestGRDBBlocking.zip](https://github.com/RxSwiftCommunity/RxGRDB/files/2083903/TestGRDBBlocking.zip)

**Comment by groue** [comment]
Hello @mayurdhaka-suryasoftware

Can you please tell me if telling the RxGRDB observable to emit in MainScheduler.instance solves the problem? `Foo.all().rx.fetchAll(in: dbPool, scheduler: MainScheduler.instance)`

Thanks

**Comment by groue** [comment]
(BTW, I'm please to discover your [dark side](https://avatars2.githubusercontent.com/u/31431205?s=400&v=4) after the [clear one](https://avatars2.githubusercontent.com/u/10453316?s=400&v=4) 😉)

**Comment by mayurdhaka-suryasoftware** [comment]
Changing `dbPool.rx.fetchTokens(in: [request], scheduler: MainScheduler.instance).mapFetch { db in ...`
to
`dbPool.rx.fetchTokens(in: [request]).mapFetch { db in` doesn't fix the issue.

**Comment by mayurdhaka-suryasoftware** [comment]
Hahaha! Yeah...

**Comment by mayurdhaka-suryasoftware** [comment]
Some further observations:

1. Changing
```
return dbPool.rx.fetchTokens(in: [request]).mapFetch { db in
            return try! Foo.fetchAll(db)
        }.subscribeOn(concurrentScheduler)
```
to 
`.subscribeOn(MainScheduler.instance)`
fixes the issue.

2.
```
return dbPool.rx.fetchTokens(in: [request]).mapFetch { db in
            return try! Foo.fetchAll(db)
        }.subscribeOn(concurrentScheduler).observeOn(MainScheduler.instance)
```
doesn't fix the issue.

**Comment by groue** [comment]
OK, @mayurdhaka-suryasoftware, thanks. I'll have a look but meanwhile don't hesitate diving in and sharing your findings: RxSwift schedulers are totally untrivial beasts, that I'm not quite mastering at all.

**Comment by groue** [comment]
I downloaded your sample project, @mayurdhaka-suryasoftware.

It indeed crashes where you says so. But I don't understand at all what you are attempting at doing, and I'm not sure at all the bug is in RxGRDB. Unfortunately, you juggle with various concurrency tools in a way that make it pretty hard do decipher. The use of `subscribe(on:)` only adds to the confusion.

I'm leaving this issue open for a few days, until you tell us the interesting bits of the solution, but I won't investigate until RxGRDB is proven to be the source of the error, sorry.

**Comment by mayurdhaka-suryasoftware** [comment]
Happy to elaborate @groue 

Here's what I'm trying to do here: I save some data to GRDB and return a Promise which resolves successfully when the data is added. I then want to test that the data has been added and use RxBlocking to test the method that returns an observable of the data.

I want the observable to get computed off the main thread, but get consumed on the main thread (which is why the `.subscribeOn(concurrentScheduler).observeOn(MainScheduler.instance)` ).
The Promise is always on the main thread so there's no context switching there.

The reason I think this is an RxGRDB issue is because such tests start failing in our production app only when I update RxGRDB.

Let me know if you require further context.

**Comment by groue** [comment]
> The reason I think this is an RxGRDB issue is because such tests start failing in our production app only when I update RxGRDB.

All right. Between RxGRDB 0.7.0 and RxGRDB 0.10.0, RxGRDB has switched its scheduling engine to regular RxSwift schedulers. With one exception, though: when you don't provide any scheduler at all:

```swift
// Custom RxGRDB scheduling
let observable = request.rx.fetchAll(in: dbQueue)
// Regular RxSwift scheduling
let observable = request.rx.fetchAll(in: dbQueue, scheduler: MainScheduler.instance)
```

That's why I requested above that you try providing a scheduler in the observable definition: so that scheduling is fully handled by RxSwift schedulers. **Please keep on using this technique** until this issue is solved.

That's also why I'm **still** not sure this is an issue with RxGRDB, and why I'd **still** like that you don't rely yet on my personal investigation. I'll help you, of course, when you're stuck. Until then, you can **still** help yourself a little:

Did you try to replace RxGRDB observables with other ones, in the same setup? Did you trace the inner behavior of toBlocking? Etc?

> I want the observable to get computed off the main thread, but get consumed on the main thread (which is why the .subscribeOn(concurrentScheduler).observeOn(MainScheduler.instance) ).

Beware with `observeOn`: RxGRDB [values observables](https://github.com/RxSwiftCommunity/RxGRDB/blob/master/README.md#values-observables) are *always* associated with a scheduler internally. A custom one when you don't specify any, or a specific one: `request.rx.fetchAll(in: dbQueue, scheduler: MainScheduler.instance)`. This means that `observeOn` is somewhat redundant, and can interfere with other scheduling techniques. You don't need to modify an RxGRDB observable with `observeOn`: instead you provide the scheduler right into the observable definition.

This means that **maybe** RxBlocking has a limitation that makes it unable to process your complex scheduling setup. **Maybe** RxSwift itself has a limitation that makes it unable to process your complex scheduling setup. But **surely** RxGRDB won't give up its [strong concurrency guarantees](https://github.com/RxSwiftCommunity/RxGRDB/blob/master/README.md#scheduling) in order to accommodate weaknesses in other libraries: **I'm still not sure the problem lies in RxGRDB**.

**Comment by groue** [comment]
@mayurdhaka-suryasoftware I'm sorry to ask, but I don't like issues to remain open if nobody cares.

Did you investigate and find an issue with RxGRDB, or not? Did you find a workaround, even if we don't know where the actual issue lies? If so, would you mind sharing your workaround so that other users can find it and escape the problem?

One day, maybe, the precise source of trouble will be isolated. And meanwhile, an alternative solution that is indexed by search engines will help users *do their job*, which is the most fundamental need of all.

Final word: don't be surprised or disappointed if the charge of the proof has weighed on your shoulders. It's called open source ecology: I can do many things, but not all things.

**Comment by mayurdhaka-suryasoftware** [comment]
Hey @groue 

I'm sorry for the delayed response. I haven't looked into this any further myself. As you've mentioned here:
> RxBlocking has a limitation that makes it unable to process your setup

I think this might be a likely scenario since I reported:
> In the test, if you change the syntax from
`let foos = try! database.fooObservableViaPool().toBlocking().first()!`
to
`let foos = try! database.fooObservableViaPool().subscribe(onNext:{ foos in /.../ })`
it works!

If further investigation of the issue on my part leads to any problem I can find related to RxGRDB, I will report back. Until then, I don't think the fault is on RxGRDB's part and I think the issue can be closed.

**Comment by groue** [comment]
That's OK, @mayurdhaka-suryasoftware ! I don't think it's time yet we poke RxBlocking maintainers. This issue will remain, ready to help whenever this trouble happens again. Happy Rx!
