### ISSUE TITLE
Linker issue when also using SQLCipher

### ISSUE THREAD

**Issue by benrudhart** [RxSwiftCommunity/RxGRDB#59]
I'm using SQLCipher with GRDB via cocoapods:
```
  pod 'GRDB.swift/SQLCipher'
  pod 'SQLCipher', '~> 4.0'
```
(from my Podfile)

This works fine. When I add RxGRDB to my setup:
` pod 'RxGRDB'`

I get this error during database initialization:
`SQLite error 21: GRDB is not linked against SQLCipher. Check https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-8-and-new-sdks/1688`

I followed the referenced manual but unfortunately it doesn't help.
Any ideas how this can be fixed?

**Comment by groue** [comment]
Sur, @benrudhart, read the doc in the RxGRDB README ;-)

**Comment by benrudhart** [comment]
🙈 totally missed that. thank you

**Comment by brunomunizaf** [comment]
Hi there,
I'm not sure if I should do this here or in another issue instead so forgive me if I'm doing it wrong. I'm facing a crash on: `
SQLITE_API void sqlite3_mutex_enter(sqlite3_mutex *p) {
  if( p ){
    assert( sqlite3GlobalConfig.mutex.xMutexEnter );
    sqlite3GlobalConfig.mutex.xMutexEnter(p);
  }
}
`

It only happens when I include `pod 'RxGRDB/SQLCipher'` and all I'm doing is trying to setup a databaseQueue: `let dbQueue = try DatabaseQueue(path: getPath())` but it crashes right away. Previously I was facing the same issue from @benrudhart  so I changed my podfile to include: `pod 'RxCocoa' pod 'RxDataSources' pod 'RxGRDB/SQLCipher'` and removed all the others (RxSwift, GRDB, SQLCipher...) Also followed what the error said and added `-framework SQLCipher` to project level build settings other linked flags.

Could anyone give me a tip here? Thanks in advance!!

XC 11.3
Simulator (iOS 12.2 - iPhone X)

**Comment by groue** [comment]
Hello @brunomunizaf,

I don't quite know what is happening. Did you happen to switch from regular SQLite to SQLCipher? I suspect a conflict between two versions of SQLite.

**Comment by brunomunizaf** [comment]
Hello @groue ,

I tried creating a fresh example project to test if is related to my code or not and turns out it worked just fine. Then I added a pod from a live debugging tool i'm using called AppSpector (not sure you've heard about it) it allows me to debug remotely whatever SQL data the app has stored. Point is: Just adding this pod to the project, not even actually starting their service was enough to make this crash happen. I removed the pod and the project works fine without it. I don't know if you want to take this as 'not my problem since GRDB works fine' or if you want to investigate what's going on here. In case you want to investigate just add `pod 'AppSpectorSDK` to your podfile and you should see what I'm talking about.

Thanks for your time, let me know if you have anything on this. Cheers.

**Comment by groue** [comment]
Thanks for the extra information. I think you are on a perfect position to perform more investigation. Who knows where the fix is? Here, in the other pod, in your app? You'll be able to contact the most suited person after this investigation.

**Comment by groue** [comment]
For example, did you check if AppSpector is compatible with SQLCipher?

**Comment by brunomunizaf** [comment]
I've been talking to them since yesterday and they said they don't support SQLCipher which is fine actually but what is bugging my brain is the way it happens. For example, they have a function which simply stops their service - Appspector.stop() - but its not enough to avoid the crash. I've created an [example project](https://github.com/brunomunizaf/testingcrypt) with just the two pods, GRDB.swift/SQLCipher + AppSpectorSDK and the only lines of code i have is let _ = try DatabaseQueue(path: ...) and it's enough to crash. One of their iOS devs said last night that he'd analyze and get back to me in case he finds anything.

**Comment by groue** [comment]
Thanks :-)

**Comment by deszip** [comment]
It's Igor from [AppSpector](https://appspector.com). I'm iOS dev Bruno talked to yesterday.

I can confirm that bad_access he found is totally on our side. Due to our SDK nature we hook lots of symbols inside the sqlite binary to integrate profiling calls. Hooking `sqlite3_open_v2` leads to bad_access on db mutex. We already have version without this hook that works just fine. I'll update you guys here when it will be released just in case someone will find this thread in future.

Regarding SQLCipher we have its support in our plans, and definitely will implement it, we receive a lot of requests for this feature. I'll also ping you guys when it will be ready.

**Comment by groue** [comment]
I should add my two cents. I think you do indeed face a linker error, which can't be fixed at runtime. Both SQLite and SQLCioher are present in your binary. They both expose the same C functions. Linker conflict.

**Comment by groue** [comment]
Thank you @deszip for chiming in, this is very much appreciated.
